# Generated by Django 5.2.1 on 2025-10-22 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demandeacces_evaluation_alter_vehicule_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_suspension',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='raison_suspension',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EN_ATTENTE', 'En attente'), ('SUSPENDU', 'Suspendu'), ('DESACTIVE', 'Désactivé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DEPART', 'Notification de départ'), ('CONFLIT', 'Résolution de conflit'), ('RETARD', 'Alerte retard'), ('SYSTEME', 'Notification système')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('reclamation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CONFLIT', 'Conflit entre chauffeurs'), ('SERVICE', 'Problème de service'), ('COMPORTEMENT', 'Mauvais comportement'), ('TECHNIQUE', 'Problème technique'), ('AUTRE', 'Autre')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'CHAUFFEUR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gare')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
